export const ADD_CONTACT_REQUEST = "ADD_CONTACT_REQUEST";
export const ADD_CONTACT_SUCCESS = "ADD_CONTACT_SUCCESS";
export const ADD_CONTACT_FAIL = "ADD_CONTACT_FAIL";

export const VIEW_REQUEST = "VIEW_REQUEST";
export const VIEW_SUCCESS = "VIEW_SUCCESS";
export const VIEW_FAIL = "VIEW_FAIL";

export const UPDATE_REQUEST = "UPDATE_REQUEST";
export const UPDATE_SUCCESS = "UPDATE_SUCCESS";
export const UPDATE_FAIL = "UPDATE_FAIL";


export const SINGLE_REQUEST = "SINGLE_REQUEST";
export const SINGLE_SUCCESS = "SINGLE_SUCCESS";
export const SINGLE_FAIL = "SINGLE_FAIL";


export const DELETE_REQUEST = "DELETE_REQUEST";
export const DELETE_SUCCESS = "DELETE_SUCCESS";
export const DELETE_FAIL = "DELETE_FAIL";


export const CLEAR_ERRORS = "CLEAR_ERRORS";
